version: '3.8'

services:
  musicbot:
    build: .
    container_name: seraphim_bot
    restart: unless-stopped
    env_file: .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
    command: python /bot.py
